resolver: lts-12.26
packages:
- .
# - ../ribosome/modules/core
# - ../ribosome/modules/test
# - ../chiasma
# - ../cornea
# - ../nvim-hs
extra-deps:
- pretty-terminal-0.1.0.0
- base-noprelude-4.11.1.0
- posix-pty-0.2.1.1
- github: neovimhaskell/nvim-hs
  commit: 63e7ef2fc40110e23240a6d0109a8bae2e29c4fa
- github: tek/cornea
  commit: 524c1093e7802295bcbfcf2b1ee28b3d8d7ccde2
- github: tek/chiasma-hs
  commit: 970bfacabc2fe06754375dcdb932cc4824dcda7b
- github: tek/ribosome-hs
  commit: 1e9c1808e55e4a82fcad110c48562d6f6b2d64ab
  subdirs:
  - modules/core
  - modules/test

