resolver: lts-12.26
packages:
- .
# - ../ribosome/modules/core
# - ../ribosome/modules/test
# - ../chiasma
# - ../cornea
# - ../nvim-hs
extra-deps:
- pretty-terminal-0.1.0.0
- base-noprelude-4.11.1.0
- posix-pty-0.2.1.1
- github: neovimhaskell/nvim-hs
  commit: 6b276629c1db1b4af9a8d33a1d6fbaf1ed46fae8
- github: tek/cornea
  commit: 90ce914ac80f4ea38c7963046857e5a14e07432c
- github: tek/chiasma
  commit: 3f224bb9cac08e0ca6b7a2bc75ba7a36b954b668
- github: tek/ribosome
  commit: 31006b2ef3d3c9b0cab149917313f215db48da36
  subdirs:
  - modules/core
  - modules/test

